import { User, Suit, Notification } from './types'

const mockUsers: User[] = [
  {
    id: '1',
    address: '0x1234567890abcdef',
    username: 'alice_sui',
    displayName: 'Alice Chen',
    bio: 'Building on Sui blockchain. Web3 enthusiast.',
    avatar: '/diverse-avatars.png',
    banner: '/celebratory-banner.png',
    location: 'San Francisco, CA',
    website: 'alice.sui',
    joinedAt: new Date('2024-01-15'),
    followersCount: 1250,
    followingCount: 342,
    isVerified: true,
  },
  {
    id: '2',
    address: '0xabcdef1234567890',
    username: 'bob_dev',
    displayName: 'Bob Developer',
    bio: 'Smart contract engineer. Move language expert.',
    avatar: '/diverse-avatars.png',
    banner: '/celebratory-banner.png',
    location: 'New York, NY',
    website: 'bob.dev',
    joinedAt: new Date('2024-02-20'),
    followersCount: 892,
    followingCount: 567,
  },
  {
    id: '3',
    address: '0x9876543210fedcba',
    username: 'charlie_nft',
    displayName: 'Charlie NFT',
    bio: 'NFT artist & collector. Sui ecosystem explorer.',
    avatar: '/diverse-avatars.png',
    banner: '/celebratory-banner.png',
    joinedAt: new Date('2024-03-10'),
    followersCount: 567,
    followingCount: 234,
  },
  {
    id: '4',
    address: '0xfedcba9876543210',
    username: 'diana_web3',
    displayName: 'Diana Web3',
    bio: 'DeFi researcher. Interested in blockchain scalability.',
    avatar: '/diverse-avatars.png',
    banner: '/celebratory-banner.png',
    joinedAt: new Date('2024-01-05'),
    followersCount: 1890,
    followingCount: 456,
    isVerified: true,
  },
  {
    id: '5',
    address: '0x1111222233334444',
    username: 'evan_crypto',
    displayName: 'Evan Crypto',
    bio: 'Crypto trader & analyst.',
    avatar: '/diverse-avatars.png',
    banner: '/celebratory-banner.png',
    joinedAt: new Date('2024-02-01'),
    followersCount: 2340,
    followingCount: 789,
  },
]

const mockSuits: Suit[] = [
  {
    id: '1',
    authorId: '1',
    author: mockUsers[0],
    content: 'Just launched my new NFT collection on Sui! Minting is now live. 🎨',
    images: [],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    likeCount: 342,
    resuitCount: 89,
    commentCount: 24,
    liked: false,
    resuited: false,
    bookmarked: false,
  },
  {
    id: '2',
    authorId: '2',
    author: mockUsers[1],
    content: 'Sui mainnet is incredibly fast. Just executed 100k transactions in seconds. This is the future.',
    images: [],
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    likeCount: 567,
    resuitCount: 234,
    commentCount: 56,
    liked: false,
    resuited: false,
    bookmarked: false,
  },
  {
    id: '3',
    authorId: '3',
    author: mockUsers[2],
    content: 'Working on a new DEX protocol for Sui. Performance metrics are looking incredible.',
    images: [],
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    likeCount: 234,
    resuitCount: 89,
    commentCount: 34,
    liked: false,
    resuited: false,
    bookmarked: false,
  },
  {
    id: '4',
    authorId: '4',
    author: mockUsers[3],
    content: 'The Sui ecosystem is growing faster than ever. So many amazing projects launching. This is just the beginning! 🚀',
    images: [],
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    likeCount: 1203,
    resuitCount: 456,
    commentCount: 123,
    liked: false,
    resuited: false,
    bookmarked: false,
  },
  {
    id: '5',
    authorId: '5',
    author: mockUsers[4],
    content: 'SUI token hitting new highs. Market sentiment is incredibly bullish right now.',
    images: [],
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
    likeCount: 789,
    resuitCount: 234,
    commentCount: 89,
    liked: false,
    resuited: false,
    bookmarked: false,
  },
]

const mockNotifications: Notification[] = [
  {
    id: '1',
    recipientId: '1',
    senderId: '2',
    sender: mockUsers[1],
    type: 'follow',
    message: 'started following you',
    read: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: '2',
    recipientId: '1',
    senderId: '3',
    sender: mockUsers[2],
    type: 'like',
    targetSuitId: '1',
    message: 'liked your Suit',
    read: false,
    createdAt: new Date(Date.now() - 60 * 60 * 1000),
  },
]

export { mockUsers, mockSuits, mockNotifications }
